# Generated by Django 3.0.8 on 2021-01-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Descrição')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name='Preço')),
                ('category', models.CharField(choices=[('boneca', 'Boneca'), ('caneta', 'Caneta com ponteira'), ('cesta_pregador_roupa', 'Cesta de pregador de roupa'), ('cobre_bolo_filo', 'Cobre-bolo de filó'), ('cueiro', 'Cueiro'), ('lapi', 'Lápis com ponteira'), ('namoradeira', 'Namoradeira de janela'), ('naninha', 'Naninha'), ('pano_prato', 'Pano de prato'), ('peso_porta', 'Peso de porta'), ('porta_absorvente', 'Porta absorvente'), ('porta_agulha', 'Porta agulha'), ('porta_calcinha infantil', 'Porta calcinha infantil'), ('porta_moeda', 'Porta moeda'), ('porta_oculos', 'Porta óculos'), ('porta_pao', 'Porta pão'), ('porta_papel_higienico', 'Porta papel higiênico'), ('puxa_saco', 'Puxa saco'), ('saida_banho_atoalhada', 'Saída de banho atoalhada'), ('toalha_mao_cozinha', 'Toalhinha de secar a mão de cozinha'), ('toalha_mao_infantil', 'Toalhinha de mão infantil'), ('touca_atoalhada_cabelo', 'Touca atoalhada pra cabelo')], max_length=100, verbose_name='Categoria')),
                ('image_1', models.ImageField(upload_to='photos/', verbose_name='Imagem principal')),
                ('image_2', models.ImageField(blank=True, upload_to='photos/', verbose_name='Segunda imagem')),
                ('image_3', models.ImageField(blank=True, upload_to='photos/', verbose_name='Terceira imagem')),
                ('image_4', models.ImageField(blank=True, upload_to='photos/', verbose_name='Quarta imagem')),
                ('image_5', models.ImageField(blank=True, upload_to='photos/', verbose_name='Quinta imagem')),
                ('image_6', models.ImageField(blank=True, upload_to='photos/', verbose_name='Sexta imagem')),
                ('wanted', models.BooleanField(default=False, verbose_name='Mais procurados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'Lista de produtos',
            },
        ),
    ]
